# Dependencies
plugins: [ jekyll-paginate ]
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "Rishabh's Blog"
tagline: 'A journal'
description: 'A journal of interesting tidbits I end up finding while picking my way across the internet'
url: http://hyde.getpoole.com
baseurl: /

author:
  name: 'Rishabh Rawat'

paginate: 3

github:
  repo: https://github.com/RishabhRawat

